remote_theme: 42bv/fortytwo
title: 'react-authentication'
description: 'Authenticating with a Spring Security application'
baseurl: /react-authentication/
plugins:
  - jekyll-remote-theme
links:
  - name: 'View on Github'
    icon: 'https://unpkg.com/simple-icons@latest/icons/github.svg'
    href: 'https://github.com/42BV/react-authentication'
